name: research_finder_jata

description: testing out capstone Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  http: ^1.2.1
  dropdown_search: ^5.0.6
  custom_otp_textfield: ^0.0.2
  flutter:
    sdk: flutter

  # english_words: ^4.0.0
  # provider: ^6.0.0
  file_picker: ^6.2.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.27.2
  provider: ^6.1.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
