name: research_finder_jata

description: testing out capstone Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  
  flutter:
    sdk: flutter
  http: ^1.1.0
  dropdown_search: ^5.0.6
  
  # Date and Time
  timeago: any
  # media
  image_picker: any
  

  english_words: ^4.0.0
  provider: ^6.0.0
  # firebase
  firebase_core: any
  firebase_auth: any
  firebase_storage: any
  cloud_firestore: any
  # state management
  email_validator: ^2.1.17
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^12.0.4 


dev_dependencies:
  
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome1.png
